development:
  adapter: postgresql
  encoding: unicode
  database: d913ub3nlbacb7
  pool: 5
  username: igzlqlmgzoqmju
  password: ZJ12Bcfe6P7e7vYkGwQnWV1XlG


# Warning:   
test: 
  adapter: postgresql
  encoding: unicode
  database: d913ub3nlbacb7
  pool: 5
  username: igzlqlmgzoqmju
  password: ZJ12Bcfe6P7e7vYkGwQnWV1XlG

production:
  adapter: postgresql
  encoding: unicode
  database: d913ub3nlbacb7
  pool: 5
  username: igzlqlmgzoqmju
  password: ZJ12Bcfe6P7e7vYkGwQnWV1XlG

